#!/usr/bin/env bash

#shellcheck disable=SC2034
declare -A options=()
declare parameters=()

bashcli-options-parse options parameters BASHCLI_CONFIG_PROFILES=profile -- "$@" || exit 1

BASHCLI_CONFIG_SCOPE=${options[scope]}

if [ "${BASHCLI_CONFIG_SCOPE}" == local ] && [ -z "${BASHCLI_CONFIG_LOCAL}" ]; then
  bashcli-fatal "local scope not supported"
fi

bashcli-config-check-profiles || exit 1
bashcli-config-check-scope || exit 1

bashcli-command-exec "${parameters[@]}"
