#!/usr/bin/env bash

declare -A options=()
declare parameters=()

bashcli-options-parse options parameters BASHCLI_CONFIG_PROFILES=profile -- "$@"

BASHCLI_CONFIG_SCOPE=${options[scope]}

if [ "${BASHCLI_CONFIG_SCOPE}" == local ] && [ -z "${BASHCLI_CONFIG_LOCAL}" ]; then
  bashcli-fatal "local scope not supported"
fi

bashcli-config-check-profiles
bashcli-config-check-scope
bashcli-command-exec "${parameters[@]}"
