#!/usr/bin/env bash

declare parameters=()
declare configFile

bashcli-options-parse '' parameters -- "$@"

if [ ${#parameters} -ne 0 ]; then
    bashcli-error "too many arguments: $*"
    exit 1
fi

configFile=$(bashcli-config-file)

exec ${EDITOR:-vi} "${configFile}"
