#!/usr/bin/env bash

declare parameters=()
declare -n commonOptions=BASHCLI_CONFIG_CLI_COMMON_OPTIONS
declare namespace=${BASHCLI_CLI_NAME}
declare configFile

bashcli-options-parse '' parameters -- "$@"

case ${#parameters} in
  0) ;;
  *) bashcli-fatal "too many arguments: $*";;
esac

if [ "${commonOptions[file]}" ]; then
  configFile="${commonOptions[file]}"
  if [ -e "${configFile}" ] && ! [ -f "${configFile}" ]; then
    bashcli-fatal "not a regular file: ${configFile}"
  fi
  if [ "${commonOptions[namespace]}" ]; then
    bashcli-warn "ignoring provided namespace"
  fi
  if [ "${commonOptions[scopes]}" ]; then
    bashcli-warn "ignoring provided scope"
  fi
else
  if [ "${commonOptions[namespace]}" ]; then
    namespace="${commonOptions[namespace]}"
  fi
    bashcli-config-files "${namespace}" "${commonOptions[scopes]:-global}"
    if [ ${#REPLY[@]} -ne 1 ]; then
      bashcli-fatal "require a single scope: ${commonOptions[scopes]}"
    fi
    configFile=${REPLY[0]}
fi

exec ${EDITOR:-vi} "${configFile}"
