#!/usr/bin/env bash

declare parameters=()
declare -n commonOptions=BASHCLI_CONFIG_CLI_COMMON_OPTIONS
declare writeOptions=()
declare command=${BASH_SOURCE##*/}

bashcli-options-parse '' parameters -- "$@"

case ${command}/${#parameters[@]} in
  set/0) bashcli-fatal "property name and value not provided";;
  set/1) bashcli-fatal "property value not provided";;
  set/2) ;;
  unset/0) bashcli-fatal "property name not provided";;
  unset/1) ;;
  *) bashcli-fatal "too many arguments: $*";;
esac

if [ "${commonOptions[namespace]}" ]; then
  writeOptions+=(-n "${commonOptions[namespace]}")
fi
if [ "${commonOptions[scopes]}" ]; then
  writeOptions+=(-s "${commonOptions[scopes]}")
fi
if [ "${commonOptions[file]}" ]; then
  writeOptions+=(-f "${commonOptions[file]}")
fi
if [ ${#BASHCLI_CONFIG_PROFILES} -gt 1 ]; then
  writeOptions+=(-P "${BASHCLI_CONFIG_PROFILES[-1]}")
fi
if [ "${command}" == unset ]; then
  writeOptions+=(-U)
fi

bashcli-config-write "${writeOptions[@]}" "${parameters[@]}"
