#!/usr/bin/env bash

declare -A options=()
declare parameters=()
declare multiOptions=()

bashcli-options-parse options parameters multiOptions=multi -- "$@"

echo "boolean=${options[boolean]}"
echo "single=${options[single]}"
for ((index = 0; index < ${#multiOptions[@]}; ++index)); do
  echo "multi[${index}]=${multiOptions[index]}"
done
echo "enum=${options[enum]}"
for ((index = 0; index < ${#parameters[@]}; ++index)); do
  echo "parameter[${index}]=${parameters[index]}"
done
