#!/usr/bin/env bash

declare -A options=()
declare parameters=()
declare multiListOptions=()
declare multiOptions=()

bashcli-options-parse \
  options parameters \
  multiListOptions=multi-list multiOptions=multi \
  -- "$@"

if [ "${options[boolean]}" ]; then
  echo "boolean=${options[boolean]}"
fi

if [ "${options[single]}" ]; then
  echo "single=${options[single]}"
fi

if [ "${options[multi]}" ]; then
  echo "multi=${options[multi]}"
fi

if [ "${options[multi-list]}" ]; then
  echo "multi-list=${options[multi-list]}"
fi

for ((index = 0; index < ${#multiListOptions[@]}; ++index)); do
  echo "multi-list[${index}]=${multiListOptions[index]}"
done

for ((index = 0; index < ${#multiOptions[@]}; ++index)); do
  echo "multi[${index}]=${multiOptions[index]}"
done

if [ "${options[enum]}" ]; then
  echo "enum=${options[enum]}"
fi

for ((index = 0; index < ${#parameters[@]}; ++index)); do
  echo "parameter[${index}]=${parameters[index]}"
done
