#!/usr/bin/env bash

# shellcheck disable=SC2034

OPTIONS=(
  boolean    boolean
  single     single
  multi      multi
  enum       single
  primary    enum:enum
  secondary  enum:enum
)

OPTION_ALIASES=(
  b boolean
  s single
  m multi
  e enum
)
