#!/usr/bin/env bash

#shellcheck disable=SC2034
declare -A options=()
declare parameters=()

bashcli-options-parse options parameters -- "$@" || exit 1

if [ "${options[load-test-lib]}" ]; then
  bashcli-load-library cli/test
fi
