#!/usr/bin/env bash

BASHCLI_DIR=$(dirname "$(realpath "$0")")
BASHCLI_CLI_NAME=${BASHCLI_CLI_NAME:-$(basename "$0")}
BASHCLI_CLI_DIR=${BASHCLI_CLI_DIR:-$(dirname $(realpath -s "$0"))}

. "${BASHCLI_DIR}"/lib/all

bashcli-command-exec "$@"
