#!/usr/bin/env bash
# shellcheck disable=SC2181

# Execute all functions having a name starting with 'test-', print the result in the TAP format and
# exit.

tests=()
readarray -t tests <<<"$(compgen -A function | grep '^test-')"

echo "1..${#tests[@]}"

for ((index = 0; index < ${#tests[@]}; ++index)); do
  test=${tests[index]}
  (set -e; ${test}) 1>&2
  if [ $? -eq 0 ]; then
    echo "ok $((index + 1)) ${test}"
  else
    echo "not ok $((index + 1)) ${test}"
  fi
done

exit 0
