#!/usr/bin/env bash

declare multiOptions=()
declare index

bashcli-options-parse '' '' multiOptions=multi-csv -- "$@"

for ((index = 0; index < ${#multiOptions[@]}; ++index)); do
  echo "multi[${index}]=${multiOptions[index]}"
done
