#!/usr/bin/env bash

# Sorts an array in place.
#
# The array is sorted with LC_ALL=C.
#
# usage: ARRAY-VARIABLE [SORT-ARGS ...]
bashcli-array-sort() {
  local -n __array=$1
  shift
  local __sortArgs=("$@")
  local IFS=$'\n'

  if [ ${#__array[@]} -gt 0 ]; then
    readarray -t __array <<<"$(LC_ALL=C sort "${__sortArgs[@]}" <<<"${__array[*]}")"
  fi
  return 0
}

bashcli-array-join() {
  local -n __array=$1
  local __separator=$2
  local IFS=${__separator}

  REPLY="${__array[*]}"
}
