#!/usr/bin/env bash

# Sorts an array in place.
#
# The array is sorted with LC_ALL=C.
#
# usage: ARRAY-VARIABLE [SORT-ARGS ...]
bashcli-array-sort() {
  local -n __array=$1
  shift
  local __sortArgs=("$@")
  local IFS=$'\n'

  if [ ${#__array[@]} -gt 0 ]; then
    readarray -t __array <<<"$(LC_ALL=C sort "${__sortArgs[@]}" <<<"${__array[*]}")"
  fi
  return 0
}

bashcli-array-reverse() {
  local -n __array=$1
  local __copy=("${__array[@]}")
  local __index

  __array=()
  for ((__index = ${#__copy[@]} - 1; __index >= 0; --__index)); do
    __array+=("${__copy[__index]}")
  done
}

bashcli-array-uniq() {
  local -n __array=$1
  local __copy=("${__array[@]}")
  local -A __elementSet=()
  local __index __element

  __array=()
  for ((__index = 0; __index < ${#__copy[@]}; ++__index)); do
    __element=${__copy[__index]}
    if [ -z "${__elementSet[${__element}]}" ]; then
      __elementSet[${__element}]=1
      __array+=("${__element}")
    fi
  done
}

bashcli-array-contains() {
  local -n __array=$1
  local __value=$2
  local __item

  for __item in "${__array[@]}"; do
    if [ "${__item}" == "${__value}" ]; then
      return 0
    fi
  done
  return 1
}
