#!/usr/bin/env bash

declare -g _BASHCLI_CACHE_DIR=${_BASHCLI_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME}/.cache}/${BASHCLI_CLI_NAME}/cache}

# Gets a value from the cache.
#
# usage: NAME [VALIDATOR]
#
# NAME is the name of the cache entry.
#
# VALIDATOR is an optional function for determining if the validity of the cache entry. It is called
# with NAME and the filename of the entry's key as arguments and should return 0, if the entry is
# still valid.
#
# FIXME: Change return style and document it.
bashcli-cache-get() {
  local name=$1
  local validator=$2
  local baseName keyFile valueFile

  -bashcli-cache-check-name "${name}"
  -bashcli-cache-check-function "${validator}"

  baseName=${_BASHCLI_CACHE_DIR}/${name}
  keyFile=${baseName}.key
  valueFile=${baseName}.value

  bashcli-debug "keyFile=${keyFile} valueFile=${valueFile}"

  if [ -f "${keyFile}" ] && [ -f "${valueFile}" ]; then
    if [ -z "${validator}" ] || "${validator}" "${name}" "${keyFile}"; then
      cat "${valueFile}"
      return $?
    fi
  fi

  rm -f -- "${keyFile}" "${valueFile}"
  return 1
}

# Puts a value into the cache.
#
# usage: NAME VALUE [KEY-FN]
#
# NAME is the name of the cache entry.
#
# VALUE is the value that should be cached.

# KEY-FN is an optional function for creating a cache-key for VALUE. It is called with NAME and the
# filename of the entry's key as arguments to which it may write the key-value and return 0.
bashcli-cache-put() {
  local name=$1
  local value=$2
  local keyFn=$3
  local baseName keyFile valueFile

  bashcli-debug "name=${name} value=${value:0:16}..."
  -bashcli-cache-check-name "${name}"
  -bashcli-cache-check-function "${keyFn}"

  baseName=${_BASHCLI_CACHE_DIR}/${name}
  keyFile=${baseName}.key
  valueFile=${baseName}.value

  mkdir -p "$(dirname "${keyFile}")"

  if [ "${keyFn}" ]; then
    "${keyFn}" "${name}" "${keyFile}"
  fi

  if ! [ -f "${keyFile}" ]; then
    touch "${keyFile}"
  fi

  printf "%s" "${value}" > "${valueFile}"
}

# Removes a value from the cache.
#
# usage: NAME
#
# NAME is the name of the cache entry to be removed.
#
# Returns 0, if the value was removed (or did not exist to begin with).
bashcli-cache-remove() {
  local name=$1
  local baseName keyFile valueFile

  -bashcli-cache-check-name "${name}"

  baseName=${_BASHCLI_CACHE_DIR}/${name}
  keyFile=${baseName}.key
  valueFile=${baseName}.value

  rm -f -- "${keyFile}" "${valueFile}"
}

-bashcli-cache-check-name() {
  local name=$1

  if [ -z "${name}" ]; then
    bashcli-error "name must not be empty"
    return 1
  fi
  if [[ ${name} == */* ]]; then
    bashcli-error "name must not contain slashes: ${name}"
    return 1
  fi
}

-bashcli-cache-check-function() {
  local fn=$1

  [ -z "${fn}" ] || declare -F -p "${fn}" &>/dev/null || {
      bashcli-error "function expected: ${fn}"
      return 1
    }
}
