#!/usr/bin/env bash
#shellcheck disable=SC2215

declare -g -a BASHCLI_COMMAND_DIRS=(
  "${XDG_CONFIG_HOME:-$HOME/.config}/${BASHCLI_CLI_NAME}/commands"
  "${BASHCLI_CLI_DIR}/commands"
)
declare -g -a BASHCLI_COMMAND_STACK=()
declare -g -a BASHCLI_COMMAND_NEXT=()

if ! [ "${BASHCLI_CLI_DIR}" -ef "${BASHCLI_DIR}" ]; then
    BASHCLI_COMMAND_DIRS+=("${BASHCLI_DIR}/commands")
fi

bashcli-command-resolve() {
  local commandList=("$@")
  local IFS=/
  local commandPath="${commandList[*]:1}"
  local commandDir directory
  unset IFS
  REPLY=
  
  for directory in "${BASHCLI_COMMAND_DIRS[@]}"; do
    commandDir=${directory}/${commandPath}
    if [ -f "${commandDir}"/main ]; then
      unset IFS
      bashcli-debug "${commandList[*]} -> ${commandDir}"
      REPLY="${commandDir}"
      return 0
    fi
  done

  bashcli-error "no such command: ${commandList[*]}"
  return 1
}

bashcli-command-exec() {
  if [ ${#BASHCLI_COMMAND_NEXT[@]} -gt 0 ]; then
    bashcli-fatal "A Command is already pending for execution, try bashcli-command-exec-2"
  fi
  BASHCLI_COMMAND_NEXT=("$@")
}

bashcli-command-exec-next() {
  set -- "${BASHCLI_COMMAND_NEXT[@]}"
  if [ $# -eq 0 ]; then
    bashcli-error "no command pending for execution"
    return 1
  fi
  BASHCLI_COMMAND_NEXT=()
  bashcli-command-exec-now "$@"
}

bashcli-command-exec-now() {
  local command
  local commandList=("${BASHCLI_COMMAND_STACK[@]}")

  if [ ${#BASHCLI_COMMAND_STACK[@]} -eq 0 ]; then
    command="${BASHCLI_CLI_NAME}"
  else
    command=$1
    commandList+=("${command}")
    shift
  fi

  if [ -z "${command}" ]; then
    bashcli-error "no command given"
    return 1
  fi

  bashcli-debug "${commandList[*]}"
  bashcli-command-resolve "${commandList[@]}" || return 1

  BASHCLI_COMMAND_STACK+=("${command}")
  -bashcli-command-local-unset command commandList
  # shellcheck source=/dev/null
  . "${REPLY}"/main "$@"
}

bashcli-command-subcommands() {
  local commandList=("$@")
  local IFS=/
  local commandPath="${commandList[*]:1}"
  local directory command commandDir
  local -A subcommands=()

  REPLY=()
  for directory in "${BASHCLI_COMMAND_DIRS[@]}"; do
    commandDir=${directory}/${commandPath}
    if [ -d "${commandDir}" ]; then
      for command in "${commandDir}"/*; do
        if [ -f "${command}"/main ]; then
          subcommands["${command##*/}"]=present
        fi
      done
    fi
  done
  REPLY=("${!subcommands[@]}")
}

bashcli-command-defines-subcommands() {
  local commandList=("$@")
  local IFS=/
  local commandPath="${commandList[*]:1}"
  local directory command commandDir

  for directory in "${BASHCLI_COMMAND_DIRS[@]}"; do
    commandDir=${directory}/${commandPath}
    if [ -f "${commandDir}"/main ]; then
      for command in "${commandDir}"/*; do
        if [ -f "${command}"/main ]; then
          return 0
        fi
      done
    fi
  done
  return 1
}

-bashcli-command-local-unset() {
  unset "$@"
}
