#!/usr/bin/env bash

# Completes files and directories.
bashcli-complete-file() {
  _comp_compgen_filedir
}

# Completes files and directories.
bashcli-complete-directory() {
  _comp_compgen_filedir -d
}

# Completes configuration profile-names.
bashcli-complete-config-profile() {
  local configFiles=() configFile

  bashcli-config-files

  for configFile in "${REPLY[@]}"; do
    if [ -f "${configFile}" ]; then
      configFiles+=("${configFile}")
    fi
  done

  readarray -t COMPREPLY < <(sed -nE 's/^[[:space:]]*%([^.]+)\..*/\1/p' "${configFiles[@]}")
}

# Completes configuration property values.
bashcli-complete-config-property() {
  local index
  bashcli-config-initialize
  bashcli-config-read

  COMPREPLY=("${!_BASHCLI_CONFIG_PROPERTIES[@]}")
  bashcli-debug "$(declare -p COMPREPLY)"
  for ((index = 0; index < ${#COMPREPLY[@]}; ++index)); do
    COMPREPLY[index]=${COMPREPLY[index]#${BASHCLI_CLI_NAME}.}
  done
}

# Completes the names of subcommands of the provided command.
bashcli-complete-subcommand() {
  local commandList=("$@")
  local completion subcommand commandMain

  if -bashcli-command-subcommands "${commandList[@]}"; then
    for subcommand in "${REPLY[@]}"; do
      if -bashcli-command-resolve "${commandList[@]}" "${subcommand}"; then
        local commandMain=${REPLY}
        -bashcli-context-read "${commandList[@]}" "${subcommand}" || continue
        completion=${_BASHCLI_CONTEXT_DESCRIPTIONS[${commandMain}]}
        bashcli-string-trim completion
        # shellcheck disable=SC2034
        BASHCLI_COMPLETIONS["${subcommand}"]=${completion%%$'\n'*}
      fi
    done
    return 0
  fi
  return 1
}

# Completes config namespaces.
bashcli-complete-namespace() {
  local configDirs=()

  if [ -d "${BASHCLI_CONFIG_DEFAULT_DIR}" ]; then
    configDirs+=("${BASHCLI_CONFIG_DEFAULT_DIR}")
  fi
  if [ -d "${BASHCLI_CONFIG_GLOBAL_DIR}" ]; then
    configDirs+=("${BASHCLI_CONFIG_GLOBAL_DIR}")
  fi
  if [ -d "${BASHCLI_CONFIG_LOCAL_DIR}" ]; then
    configDirs+=("${BASHCLI_CONFIG_LOCAL_DIR}")
  fi

  readarray -d '' -t COMPREPLY < <(find "${configDirs[@]}" -mindepth 1 -maxdepth 1 -type f -name '*.conf' -printf '%f\0')
  COMPREPLY=("${COMPREPLY[@]/.conf/}")
}

# Complete resource scopes.
bashcli-complete-resource-scope() {
  COMPREPLY=(all none builtin default global project local)
  COMPREPLY+=(~builtin ~default ~global ~project ~local)
}
