#!/usr/bin/env bash

# shellcheck disable=SC2034,SC2004

bashcli-complete-directory() {
  local completion

  _comp_compgen_filedir -d

  for completion in "${COMPREPLY[@]}"; do
    BASHCLI_COMPLETIONS[${completion}]=''
  done

  COMPREPLY=()
}

bashcli-complete-file() {
  local completion

  _comp_compgen_filedir

  for completion in "${COMPREPLY[@]}"; do
    BASHCLI_COMPLETIONS[${completion}]=''
  done

  COMPREPLY=()
}

bashcli-complete-config-profile() {
  local profile

  bashcli-config-initialize

  for profile in "${!BASHCLI_CONFIG_KNOWN_PROFILES[@]}"; do
    BASHCLI_COMPLETIONS[${profile}]=''
  done
}
