#!/usr/bin/env bash

bashcli-complete-directory() {
  local completion

  _comp_compgen_filedir -d

  for completion in "${COMPREPLY[@]}"; do
    BASHCLI_COMPLETIONS[${completion}]=''
  done

  COMPREPLY=()
}

bashcli-complete-file() {
  local completion

  _comp_compgen_filedir

  for completion in "${COMPREPLY[@]}"; do
    BASHCLI_COMPLETIONS[${completion}]=''
  done

  COMPREPLY=()
}

bashcli-complete-config-profile() {
  local profile

  bashcli-config-initialize

  for profile in "${!BASHCLI_CONFIG_KNOWN_PROFILES[@]}"; do
    # shellcheck disable=SC2034
    BASHCLI_COMPLETIONS[${profile}]=''
  done
}

bashcli-complete-config-property() {
  local property

  bashcli-config-initialize

  for property in "${!BASHCLI_CONFIG_PROPERTIES[@]}"; do
    # shellcheck disable=SC2034
    BASHCLI_COMPLETIONS[${property}]=''
  done
}
