#!/usr/bin/env bash
# shellcheck disable=SC2034

declare -g -A BASHCLI_CONTEXT_DESCRIPTIONS=()
declare -g -A BASHCLI_CONTEXT_OPTIONS=()
declare -g -A BASHCLI_CONTEXT_OPTION_DESCRIPTIONS=()
declare -g -A BASHCLI_CONTEXT_OPTION_ALIASES=()
declare -g -A BASHCLI_CONTEXT_OPTION_COMPLETIONS=()
declare -g -A BASHCLI_CONTEXT_CONFIG=()
declare -g -A BASHCLI_CONTEXT_OPTIONS_SOURCE=()
declare -g -A BASHCLI_CONTEXT_READ=()

declare -g -a BASHCLI_CONTEXT_DEFAULT_OPTIONS=(version help)
declare -g -r BASHCLI_CONTEXT_NOT_DOCUMENTED='Not documented.'

bashcli-context-clear() {
  BASHCLI_CONTEXT_DESCRIPTIONS=()
  BASHCLI_CONTEXT_OPTIONS=()
  BASHCLI_CONTEXT_OPTION_DESCRIPTIONS=()
  BASHCLI_CONTEXT_OPTION_ALIASES=()
  BASHCLI_CONTEXT_OPTION_COMPLETIONS=()
  BASHCLI_CONTEXT_CONFIG=()
  BASHCLI_CONTEXT_OPTIONS_SOURCE=()
  BASHCLI_CONTEXT_READ=()
  bashcli-debug "context cleared"
}

bashcli-context-read() {
  local DESCRIPTION=
  local -A OPTIONS=()
  local -A OPTION_DESCRIPTIONS=()
  local -A OPTION_ALIASES=()
  local -A OPTION_COMPLETIONS=()
  local -A CONFIG=()
  local commandMain=$1
  local commandContext=${commandMain}.context

  if [ -z "${BASHCLI_CONTEXT_READ[${commandMain}]}" ]; then
    if [ -f "${commandContext}" ]; then
      bashcli-debug "${commandContext}"
      # shellcheck source=/dev/null
      . "${commandContext}"
      bashcli-context-validate
      bashcli-context-defaults
      bashcli-context-merge "${commandMain}"
      BASHCLI_CONTEXT_READ[${commandMain}]=true
    fi
  fi
}

bashcli-context-merge() {
  local alias option commandMain=$1
  for option in "${!OPTIONS[@]}"; do
    BASHCLI_CONTEXT_DESCRIPTIONS["${commandMain}"]=${DESCRIPTION}
    BASHCLI_CONTEXT_OPTIONS[${option}]=${OPTIONS[${option}]}
    BASHCLI_CONTEXT_OPTION_DESCRIPTIONS[${option}]=${OPTION_DESCRIPTIONS[${option}]}
    BASHCLI_CONTEXT_OPTION_COMPLETIONS[${option}]=${OPTION_COMPLETIONS[${option}]}
    BASHCLI_CONTEXT_OPTIONS_SOURCE[${option}]=${commandMain}
  done

  for alias in "${!OPTION_ALIASES[@]}"; do
    BASHCLI_CONTEXT_OPTION_ALIASES[${alias}]=${OPTION_ALIASES[${alias}]}
  done
}

bashcli-context-defaults() {
  if [ -z "${OPTIONS[help]}" ]; then
    OPTIONS[help]=boolean
    OPTION_DESCRIPTIONS[help]="Shows a help message."
  fi
  if [ -z "${OPTIONS[version]}" ]; then
    OPTIONS[version]=boolean
    OPTION_DESCRIPTIONS[version]="Prints the version of the program."
  fi
}

bashcli-context-validate() {
  local option optionType alias IFS

  for option in "${!OPTIONS[@]}"; do
    if [[ ${option} == -* ]]; then
      bashcli-fatal "Option name must not start with a dash: ${option}"
    fi
    optionType=${OPTIONS[${option}]}
    case ${optionType} in
      boolean|single|multi) ;;
      enum:?*)
        case ${OPTIONS[${optionType#enum:}]} in
          multi|boolean|enum:*)
            bashcli-fatal "Enum option-value must be a single option: ${optionType:#enum:}" ;;
        esac ;;
      *) bashcli-fatal "Option-type must be one of boolean, single, multi or enum:\${name}: ${optionType}" ;;
    esac
    if [ -z "${OPTION_DESCRIPTIONS[${option}]}" ]; then
      OPTION_DESCRIPTIONS[${option}]="${BASHCLI_CONTEXT_NOT_DOCUMENTED}"
    fi
  done

  for option in "${!OPTION_DESCRIPTIONS[@]}"; do
    if [ -z "${OPTIONS[${option}]}" ]; then
      bashcli-warn "Description for non-existing option provided: ${option}"
      unset "OPTION_DESCRIPTIONS[${option}]"
    fi
  done

  for alias in "${!OPTION_ALIASES[@]}"; do
    option=${OPTION_ALIASES[${alias}]}
    if [ -z "${OPTIONS[${option}]}" ]; then
      bashcli-warn "Alias for non-existing option provided: ${alias} -> ${option}"
      unset "OPTION_ALIASES[${option}]"
    fi
  done
  
  for alias in "${!OPTION_ALIASES[@]}"; do
    if [[ ${alias} == -* ]]; then
      bashcli-fatal "Alias name must not start with a dash: ${alias}"
    fi
  done

  for option in "${!OPTION_COMPLETIONS[@]}"; do
    if [ "${option}" == %parameter ]; then
      continue
    fi
    if [ -z "${OPTIONS[${option}]}" ]; then
      bashcli-warn "Completions for non-existing option provided: ${option}"
      unset "OPTION_COMPLETIONS[${option}]"
    fi
  done
}
