#!/usr/bin/env bash
# shellcheck disable=SC2190,SC2064,SC2184,SC2215,SC2207

declare -g -A BASHCLI_HELP_FACES=(
  bold $'\033[1m'
  regular $'\033[0m'
)

if ! [ -t 1 ]; then
  BASHCLI_HELP_FACES=()
fi

declare -g BASHCLI_HELP_WIDTH=$(( ${COLUMNS:-80} < 80 ? ${COLUMNS:-80} : 80))

# shellcheck disable=SC2215
bashcli-help-show() {
  local commandList=("$@")
  local commandMain

  trap "$(shopt -p extglob)" EXIT RETURN
  shopt -s extglob

  bashcli-debug "${commandList[*]}"
  bashcli-command-resolve "${commandList[@]}" || return 1
  commandMain=${REPLY}
  bashcli-context-clear
  bashcli-context-read "${commandMain}"

  -bashcli-help-show-intro "${commandMain}" "${commandList[@]}"
  -bashcli-help-show-options
  -bashcli-help-show-subcommands "${commandList[@]}"
}

-bashcli-help-show-intro() {
  local commandMain=$1
  shift
  local commandList=("$@")
  local description=${BASHCLI_CONTEXT_DESCRIPTIONS[${commandMain}]}
  local optionsInfo parameterInfo parameterTypes

  bashcli-string-trim description

  if [ ${#BASHCLI_CONTEXT_OPTIONS[@]} -gt 0 ]; then
    optionsInfo=" [ OPTIONS ]"
  fi
  parameterTypes="${BASHCLI_CONTEXT_OPTION_COMPLETIONS[%parameter]}"
  if [ -n "${parameterTypes}" ]; then
    parameterTypes=${parameterTypes//,/ | }
    parameterInfo=" ${parameterTypes^^} ..."
  fi

  commandList[0]=${BASHCLI_CLI_NAME}
  printf "%sUsage:%s\n%s%s%s\n" "${BASHCLI_HELP_FACES[bold]}" "${BASHCLI_HELP_FACES[regular]}" \
         "${commandList[*]}" "${optionsInfo}" "${parameterInfo}"
  if [ -n "${description}" ]; then
    fmt --width "${BASHCLI_HELP_WIDTH}" <<<$'\n'"${description%%*($'\n')}"
  fi
}

# shellcheck disable=SC2206,SC2004
-bashcli-help-show-options() {
  local -A optionLabels=()
  local index optionDashes option optionAliases optionVariants optionVariant
  local optionValueType optionType optionLabel description
  local options=($(-bashcli-help-sorted-options))


  for option in "${options[@]}"; do
    # Accumulate options and their aliases as variants, add dash-prefixes and then sort them.
    bashcli-option-aliases "${option}"
    optionAliases=("${REPLY[@]}")
    optionVariants=(${option} "${optionAliases[@]}")
    for ((index = 0; index < ${#optionVariants[@]}; ++index)); do
      optionVariant=${optionVariants[${index}]}
      optionDashes=${optionVariant:0:2}
      optionDashes=${optionDashes//?/-}
      optionVariants[${index}]=${optionDashes}${optionVariant}
    done
    optionVariants=($(LC_ALL=C sort <<<"${optionVariants[*]}"))

    # Build the label starting with variants, then add their value type and store the result.
    optionLabel=
    for ((index = 0; index < ${#optionVariants[@]}; ++index)); do
      if [ ${index} -gt 0 ]; then
        optionLabel+=', '
      fi
      optionLabel+=${optionVariants[${index}]}
    done

    optionType=${BASHCLI_CONTEXT_OPTIONS[${option}]}
    case ${optionType} in
      single|multi)
        optionValueType=${BASHCLI_CONTEXT_OPTION_COMPLETIONS[${option}]:-OPTION}
        optionValueType=${optionValueType//,/ | }
        optionLabel+=" ${optionValueType^^}"
    esac
    optionLabels[${option}]=${optionLabel}
  done

  # Now print the options with their description.
  if [ ${#optionLabels[@]} -gt 0 ]; then
    printf "\n%sOptions:%s\n" "${BASHCLI_HELP_FACES[bold]}" "${BASHCLI_HELP_FACES[regular]}"
    for ((index = 0; index < ${#options[@]}; ++index)); do
      option=${options[index]}
      if [ ${index} -gt 0 ]; then
        echo
      fi
      printf "%s\n" "${optionLabels[${option}]}"
      description=${BASHCLI_CONTEXT_OPTION_DESCRIPTIONS[${option}]}
      fmt --width "$((${BASHCLI_HELP_WIDTH} - 2))"  <<< "${description%%*($'\n')}" | pr --indent 2 --omit-pagination
    done
  fi
}

-bashcli-help-show-subcommands() {
  local commandList=("$@")
  local maxSubcommandLength=0
  local padding=4
  local subcommand subcommand description

  if bashcli-command-subcommands "${commandList[@]}"; then
    printf "\n%sSubcommands:%s\n" "${BASHCLI_HELP_FACES[bold]}" "${BASHCLI_HELP_FACES[regular]}"

    for subcommand in "${REPLY[@]}"; do
      if [ ${#subcommand} -gt "${maxSubcommandLength}" ]; then
        maxSubcommandLength=${#subcommand}
      fi
    done

    ((maxSubcommandLength += padding))
    for subcommand in "${REPLY[@]}"; do
      bashcli-command-resolve "${commandList[@]}" "${subcommand}"
      commandMain=${REPLY}
      if [ -n "${commandMain}" ]; then
        bashcli-context-read "${commandMain}"
      fi
      description=${BASHCLI_CONTEXT_DESCRIPTIONS[${commandMain}]}
      bashcli-string-trim description
      printf "%-${maxSubcommandLength}s%s\n" "${subcommand}" "${description}"
    done
  fi
}

# shellcheck disable=SC2207
-bashcli-help-sorted-options() {
  local index option default
  local IFS=$'\n'
  local options=($(LC_ALL=C sort <<<"${!BASHCLI_CONTEXT_OPTIONS[@]}"))
  for ((index = 0; index < ${#options[@]}; ++index)); do
    option=${options[index]}
    for default in "${BASHCLI_CONTEXT_DEFAULT_OPTIONS[@]}"; do
      if [ "${option}" == "${default}" ]; then
        break
      fi
      default=
    done
    if [ -z "${default}" ]; then
      printf "%s\n" "${option}"
    fi
  done
  for option in "${BASHCLI_CONTEXT_DEFAULT_OPTIONS[@]}"; do
    if [ "${BASHCLI_CONTEXT_OPTIONS[${option}]}" ]; then
      printf "%s\n" "${option}"
    fi
  done
}
