#!/usr/bin/env bash

declare -g -A _BASHCLI_LIBRARIES_LOADED=()
declare -g -A _BASHCLI_COLORS=(
  error  $'\033[91m'
  warn   $'\033[93m'
  debug  $'\033[96m'
  info   $'\033[92m'
  none   $'\033[39m'
)

if ! [ -t 2 ]; then
  _BASHCLI_COLORS=()
fi

bashcli-debug() {
  case ${BASHCLI_DEBUG} in
    false|'') return 0 ;;
  esac

  local IFS=' '
  local context
  local fnName
  local minContextWidth=24
  local cliName=${BASHCLI_CLI_NAME}

  if [[ -n "${FUNCNAME[1]}" && "${FUNCNAME[1]}" != source ]]; then
    fnName="${FUNCNAME[1]}"
    if [[ ${fnName} == ?(-)bashcli-* ]]; then
      fnName=${fnName#-}
      fnName=${fnName#bashcli-}
    elif [[ ${fnName} == ${cliName}-* ]]; then
      fnName=${fnName#${cliName}-}
    fi
    context+="${fnName}"
  elif [ ${#_BASHCLI_COMMAND_STACK[@]} -gt 1 ]; then
    context="${_BASHCLI_COMMAND_STACK[*]:1}"
  else
    context="${_BASHCLI_COMMAND_STACK[*]}"
  fi

  if [ "${BASHCLI_DEBUG}" != true ] && ! [[ "${context}" =~ ${BASHCLI_DEBUG} ]]; then
    return 0
  fi

  printf "[%s]%-${minContextWidth}s %s\n" "${_BASHCLI_COLORS[debug]}debug${_BASHCLI_COLORS[none]}" "(${context})" "${*//$'\n'/\\n}" >&2
}

bashcli-info() {
  local IFS=' '
  printf "[%s] %s\n" "${_BASHCLI_COLORS[info]}info${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-warn() {
  local IFS=' '
  printf "[%s] %s\n" "${_BASHCLI_COLORS[warn]}warn${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-error() {
  local IFS=' '
  printf "[%s] %s\n" "${_BASHCLI_COLORS[error]}error${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-fatal() {
  bashcli-error "$@"
  exit 1
}

bashcli-debug-command() {
  local command=("$@")
  local quoted=()
  local argument index

  for ((index = 0; index < ${#command[@]}; ++index)); do
    argument=${command[index]}
    bashcli-string-quote argument
    quoted+=("${argument}")
  done

  bashcli-debug "${quoted[@]}"
}

bashcli-load-library() {
  local library=$1
  local libraryDirectories=("${BASHCLI_CLI_DIR}/lib" "${BASHCLI_DIR}/lib")
  local directory=

  if [[ "${_BASHCLI_LIBRARIES_LOADED[${library}]}" == true && "${BASHCLI_DEBUG}" != true ]]; then
    return 0
  else
    for directory in "${libraryDirectories[@]}"; do
      if [ -f "${directory}/${library}" ]; then
        _BASHCLI_LIBRARIES_LOADED[${library}]=true
        . "${directory}/${library}"
        return 0
      fi
    done
  fi
  bashcli-error "library ${library} not found in ${libraryDirectories[*]}" >&2
  return 1
}

eval "${BASHCLI_CLI_NAME}() {
  \"${BASHCLI_CLI_SCRIPT}\" \"\$@\"
}"

bashcli-load-library bashcli/array
bashcli-load-library bashcli/cache
bashcli-load-library bashcli/resources
bashcli-load-library bashcli/command
bashcli-load-library bashcli/config
bashcli-load-library bashcli/context
bashcli-load-library bashcli/help
bashcli-load-library bashcli/options
bashcli-load-library bashcli/string
