#!/usr/bin/env bash

:
# shellcheck disable=SC2034
declare -g -A BASHCLI_TTY_STYLES=(
  error   $'\033[91m'
  warn    $'\033[93m'
  debug   $'\033[96m'
  info    $'\033[92m'
  success $'\033[92m'
  failure $'\033[91m'
  bold    $'\033[1m'
  none    $'\033[39m'
)

if [ -t 1 ]; then
  declare -n BASHCLI_TTY_STDOUT_STYLES=BASHCLI_TTY_STYLES
else
  # shellcheck disable=SC2034
  declare -g -A BASHCLI_TTY_STDOUT_STYLES=()
fi

if [ -t 2 ]; then
  declare -n BASHCLI_TTY_STDERR_STYLES=BASHCLI_TTY_STYLES
else
  # shellcheck disable=SC2034
  declare -g -A BASHCLI_TTY_STDERR_STYLES=()
fi

declare -g -A _BASHCLI_LIBRARIES_LOADED=()

bashcli-debug() {
  case ${BASHCLI_DEBUG} in
    false|'') return 0 ;;
  esac

  local IFS=' '
  local context
  local fnName
  local minContextWidth=24
  local cliName=${BASHCLI_CLI_NAME}
  local -n styles=BASHCLI_TTY_STDERR_STYLES

  if [[ -n "${FUNCNAME[1]}" && "${FUNCNAME[1]}" != source ]]; then
    fnName="${FUNCNAME[1]}"
    if [[ ${fnName} == ?(-)bashcli-* ]]; then
      fnName=${fnName#-}
      fnName=${fnName#bashcli-}
    elif [[ ${fnName} == ${cliName}-* ]]; then
      fnName=${fnName#${cliName}-}
    fi
    context+="${fnName}"
  elif [ ${#_BASHCLI_COMMAND_STACK[@]} -gt 1 ]; then
    context="${_BASHCLI_COMMAND_STACK[*]:1}"
  else
    context="${_BASHCLI_COMMAND_STACK[*]}"
  fi

  if [ "${BASHCLI_DEBUG}" != true ] && ! [[ "${context}" =~ ${BASHCLI_DEBUG} ]]; then
    return 0
  fi

  printf "[%s]%-${minContextWidth}s %s\n" "${styles[debug]}debug${styles[none]}" "(${context})" "${*//$'\n'/\\n}" >&2
}

bashcli-info() {
  local IFS=' '
  local -n styles=BASHCLI_TTY_STDERR_STYLES
  printf "[%s] %s\n" "${styles[info]}info${styles[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-warn() {
  local IFS=' '
  local -n styles=BASHCLI_TTY_STDERR_STYLES
  printf "[%s] %s\n" "${styles[warn]}warn${styles[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-error() {
  local IFS=' '
  local -n styles=BASHCLI_TTY_STDERR_STYLES
  printf "[%s] %s\n" "${styles[error]}error${styles[none]}" "${*//$'\n'/\\n}" >&2
}

bashcli-fatal() {
  bashcli-error "$@"
  exit 1
}

bashcli-debug-command() {
  local command=("$@")
  local quoted=()
  local argument index

  for ((index = 0; index < ${#command[@]}; ++index)); do
    argument=${command[index]}
    bashcli-string-quote argument
    quoted+=("${argument}")
  done

  bashcli-debug "${quoted[@]}"
}

bashcli-load-library() {
  local library=$1
  local libraryDirectories=("${BASHCLI_CLI_DIR}/lib" "${BASHCLI_DIR}/lib")
  local directory=

  if [[ "${_BASHCLI_LIBRARIES_LOADED[${library}]}" == true && "${BASHCLI_DEBUG}" != true ]]; then
    return 0
  else
    for directory in "${libraryDirectories[@]}"; do
      if [ -f "${directory}/${library}" ]; then
        _BASHCLI_LIBRARIES_LOADED[${library}]=true
        . "${directory}/${library}"
        return 0
      fi
    done
  fi
  bashcli-error "library ${library} not found in ${libraryDirectories[*]}" >&2
  return 1
}

eval "${BASHCLI_CLI_NAME}() {
  \"${BASHCLI_CLI_SCRIPT}\" \"\$@\"
}"

bashcli-load-library bashcli/array
bashcli-load-library bashcli/cache
bashcli-load-library bashcli/resource-scopes
bashcli-load-library bashcli/command
bashcli-load-library bashcli/config
bashcli-load-library bashcli/context
bashcli-load-library bashcli/help
bashcli-load-library bashcli/options
bashcli-load-library bashcli/string
