#!/usr/bin/env bash

declare -ga BASHCLI_RESOURCE_SCOPES=(builtin default global)
declare -gA BASHCLI_RESOURCE_SCOPES_DIRS=(
  builtin "${BASHCLI_DIR}"
  default "${BASHCLI_CLI_DIR}"
  global  "${BASHCLI_GLOBAL_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/${BASHCLI_CLI_NAME}}"
)

[ "${BASHCLI_PROJECT_DIR}" ] && {
  BASHCLI_RESOURCE_SCOPES+=(project)
  # shellcheck disable=SC2154,SC2034
  BASHCLI_RESOURCE_SCOPES_DIRS[project]=${BASHCLI_PROJECT_DIR}
}
[ "${BASHCLI_LOCAL_DIR}" ] && {
  BASHCLI_RESOURCE_SCOPES+=(local)
  # shellcheck disable=SC2154,SC2034
  BASHCLI_RESOURCE_SCOPES_DIRS[local]=${BASHCLI_LOCAL_DIR}
}

# shellcheck disable=SC2165,SC2167
bashcli-resource-scopes-parse() {
  local -A resolvedScopes=()
  local scope scopes excluded
  local IFS
  REPLY=()

  bashcli-string-split "$1" , scopes

  for scope in "${scopes[@]}"; do
    bashcli-string-trim scope
    case ${scope} in
      builtin|default|global|project|local)
        if [ -z "${BASHCLI_RESOURCE_SCOPES_DIRS[${scope}]}" ]; then
          bashcli-error "scope not supported by this program: ${scope}"
          return 1
        fi
        resolvedScopes[${scope}]=set ;;
      (~@(builtin|default|global|project|local))
      excluded=${scope:1}
      for scope in "${BASHCLI_RESOURCE_SCOPES[@]}"; do
        if [ "${scope}" != "${excluded}" ]; then
          resolvedScopes[${scope}]=set
        else
          resolvedScopes[${scope}]=
        fi
      done;;
      none|~all) resolvedScopes=() ;;
      all|~none)
        resolvedScopes=()
        for scope in "${BASHCLI_RESOURCE_SCOPES[@]}"; do
          resolvedScopes[${scope}]=set
        done ;;
      *) bashcli-error "unknown scope: ${scope}"
         return 1;;
    esac
  done

  for scope in "${BASHCLI_RESOURCE_SCOPES[@]}"; do
    if [ "${resolvedScopes[${scope}]}" ]; then
      REPLY+=("${scope}")
    fi
  done

  IFS=' '
  bashcli-debug "$1 -> ${REPLY[*]}"
}

bashcli-resource-scopes-resolve() {
  local OPTIND=1
  local scopesOption=all
  local all scope scopes resource reverse option directory filename

  REPLY=()
  while getopts "s:ra" option "$@"; do
    case ${option} in
      s) scopesOption=${OPTARG};;
      r) reverse=true;;
      a) all=true;;
      *) return 1;;
    esac
  done
  shift "$((OPTIND - 1))"

  if [ $# -ne 1 ]; then
    bashcli-error "require exactly one resource: $*"
    return 1
  fi
  if [ -z "$1" ]; then
    bashcli-error "resource must not be the empty string"
    return 1
  fi

  resource=$1

  bashcli-resource-scopes-parse "${scopesOption}"
  scopes=("${REPLY[@]}")

  if [ "${reverse}" ]; then
    bashcli-array-reverse scopes
  fi

  REPLY=()
  for scope in "${scopes[@]}"; do
    directory=${BASHCLI_RESOURCE_SCOPES_DIRS[${scope}]}
    filename=${directory}/${resource}
    if [ -e "${filename}" ]; then
      bashcli-debug "${scope} ${resource} ${filename}"
      REPLY+=("${filename}")
      if [ -z "${all}" ]; then
        return 0
      fi
    fi
  done

  if [ ${#REPLY[@]} -gt 0 ]; then
    return 0
  else
    bashcli-debug "${scope} ${resource} <none>"
    return 1
  fi
}

bashcli-resource-scopes-unparse() {
  local IFS=,
  REPLY="$*"
}
