#!/usr/bin/env bash

declare -ga BASHCLI_RESOURCE_SCOPES=(builtin default global)
declare -gA BASHCLI_RESOURCE_DIRS=(
  builtin "${BASHCLI_DIR}"
  default "${BASHCLI_CLI_DIR}"
  global  "${BASHCLI_GLOBAL_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/${BASHCLI_CLI_NAME}}"
)

[ "${BASHCLI_PROJECT_DIR}" ] && {
  BASHCLI_RESOURCE_SCOPES+=(project)
  # shellcheck disable=SC2154,SC2034
  BASHCLI_RESOURCE_DIRS[project]=${BASHCLI_PROJECT_DIR}
}
[ "${BASHCLI_LOCAL_DIR}" ] && {
  BASHCLI_RESOURCE_SCOPES+=(local)
  # shellcheck disable=SC2154,SC2034
  BASHCLI_RESOURCE_DIRS[local]=${BASHCLI_LOCAL_DIR}
}

# shellcheck disable=SC2165,SC2167
bashcli-resource-parse-scopes() {
  local -A resolvedScopes=()
  local scope scopes
  REPLY=()

  bashcli-string-split "$1" , scopes

  for scope in "${scopes[@]}"; do
    bashcli-string-trim scope
    case ${scope} in
      builtin|default|global|project|local)
        if [ -z "${BASHCLI_RESOURCE_DIRS[${scope}]}" ]; then
          bashcli-error "scope not supported by this program: ${scope}"
          return 1
        fi
        resolvedScopes[${scope}]=set ;;
      (~@(builtin|default|global|project|local))
      resolvedScopes[${scope}]= ;;
      none|~all) resolvedScopes=() ;;
      all|~none)
        resolvedScopes=()
        for scope in "${BASHCLI_RESOURCE_SCOPES[@]}"; do
          resolvedScopes[${scope}]=set
        done ;;
      *) bashcli-error "unknown scope: ${scope}"
         return 1;;
    esac
  done
  for scope in "${BASHCLI_RESOURCE_SCOPES[@]}"; do
    if [ "${resolvedScopes[${scope}]}" ]; then
      REPLY+=("${scope}")
    fi
  done

  bashcli-debug "$1 -> ${REPLY[*]}"
}

bashcli-resource-get() {
  local OPTIND=1
  local scopesOption=all
  local scope scopes resource reverse option directory filename

  REPLY=
  while getopts "s:r" option "$@"; do
    case ${option} in
      s) scopesOption=${OPTARG};;
      r) reverse=true;;         # FIXME: reverse should be the opposite
      *) return 1;;
    esac
  done
  shift "$((OPTIND - 1))"

  if [ $# -ne 1 ]; then
    bashcli-error "too many arguments"
    return 1
  fi
  resource=$1

  bashcli-resource-parse-scopes "${scopesOption}"
  scopes=("${REPLY[@]}")

  if [ "${reverse}" ]; then
    bashcli-array-reverse scopes
  fi

  for scope in "${scopes[@]}"; do
    directory=${BASHCLI_RESOURCE_DIRS[${scope}]}
    filename=${directory}/${resource}
    if [ -f "${filename}" ]; then
      REPLY=${filename}
      return 0
    fi
  done
  return 1
}
