#!/usr/bin/env bash

bashcli-string-trim() {
  local -n _string

  for _string; do
    _string=${_string##+([ $'\t\r\n'])}
    _string=${_string%%+([ $'\t\r\n'])}
  done
}

bashcli-string-quote() {
  local -n _string

  for _string; do
    if [[ ${_string} != *([a-zA-Z0-9,._+:@%/-]) ]]; then
      _string=${_string@Q}
    fi
  done
}
