#!/usr/bin/env bash

# shellcheck disable=SC2034,SC2054

DESCRIPTION="\
This command is for testing only.

It is otherwise a super subcommand.
"

OPTIONS=(
  xenum-option         single
  xboolean-option      boolean
  xsingle-option       single
  xmulti-option        multi
  xenum-option-first   enum:enum-option
  xenum-option-second  enum:enum-option
  xenum-option-third   enum:enum-option
)

OPTION_DESCRIPTIONS=(
  xboolean-option "An option without an argument."
  xsingle-option  "An option with an argument that is supposed to be used only once."
  xmulti-option   "An option with an argument that may be used multiple times."
)

OPTION_ALIASES=(
  xboolean-option x,X
  xsingle-option  s,S
  xmulti-option   m,M
)

OPTION_COMPLETIONS=(
  xsingle-option file
  xmulti-option  directory,service
)

CONFIG=(
)
