#!/usr/bin/env bash

bashcli-log-debug "Test subcommand called with arguments $*"

declare -A options=()
declare parameters=()
declare -a multiOptionOptions=()

bashcli-options-parse options parameters multiOptionOptions -- "$@" || {
  bashcli-fatal "Failed to parse options"
}

bashcli-log-debug "Options successfully parsed"

declare -p options
declare -p parameters
declare -p multiOptionOptions
