#!/usr/bin/env bash


declare -A options=()
declare -a profiles=()
declare parameters=()

bashcli-options-parse options parameters profiles=profile -- "$@"

if [ "${options[version]}" ]; then
  printf "%s %s (bashcli %s)\n" "${BASHCLI_CLI_NAME}" "${BASHCLI_CLI_VERSION:-unknown}" "${BASHCLI_VERSION}"
  exit 0
fi

if [ "${options[debug]}" ]; then
  export BASHCLI_DEBUG=${BASHCLI_DEBUG:-true}
fi
if [ "${options[debug-filter]}" ]; then
  case "${BASHCLI_DEBUG}" in
    true|false) BASHCLI_DEBUG= ;;
  esac
  export BASHCLI_DEBUG="${BASHCLI_DEBUG+(${BASHCLI_DEBUG})|}${options[debug-filter]}"
fi


bashcli-config-initialize "${profiles[@]}"
bashcli-command-exec "${parameters[@]}"
