#!/usr/bin/env bash

#shellcheck disable=SC2034
declare -A options=()
declare parameters=()

bashcli-options-parse options parameters -- "$@" || exit 1

[ ${#parameters[@]} -eq 0 ] && {
  bashcli-error "no command given"
  exit 1
}

bashcli-command-exec "${parameters[@]}"
