#!/usr/bin/env bash

#shellcheck disable=SC2034

bashcli-debug "Showing help for command $*"

declare -A options=()
declare parameters=()

bashcli-options-parse options parameters -- "$@"
bashcli-help-show . "$@"
