#!/usr/bin/env bash

#shellcheck disable=SC2034
declare -A options=()
declare parameters=()

bashcli-options-parse options parameters -- "$@" || exit 1

if [ ${#parameters[@]} -gt 0 ]; then
  bashcli-command-exec "${parameters[@]}"
fi
