#!/usr/bin/env bash

declare -a BASHCLI_COMMAND_DIRS=(
  "${XDG_CONFIG_HOME:-$HOME/.config}/${BASHCLI_CLI_NAME}/commands"
  "${BASHCLI_CLI_DIR}/commands"
)
declare -a BASHCLI_COMMAND_STACK=()

if ! [ "${BASHCLI_CLI_DIR}" -ef "${BASHCLI_DIR}" ]; then
    BASHCLI_COMMAND_DIRS+=("${BASHCLI_DIR}/commands")
fi

bashcli-command-resolve() {
  local commandList=("$@")
  local IFS=/
  local commandPath="${commandList[*]:1}"
  local commandDir directory
  unset IFS
  REPLY=
  
  for directory in "${BASHCLI_COMMAND_DIRS[@]}"; do
    commandDir=${directory}/${commandPath}
    if [ -f "${commandDir}"/main ]; then
      unset IFS
      bashcli-log-debug "${commandList[*]} -> ${commandDir}"
      REPLY="${commandDir}"
      return 0
    fi
  done

  bashcli-log-warning "Command not found: ${commandList[*]}"
  return 1
}

bashcli-command-exec() {
  local command commandDir
  local commandList=("${BASHCLI_COMMAND_STACK[@]}")

  if [ ${#BASHCLI_COMMAND_STACK[@]} -eq 0 ]; then
    command=${BASHCLI_CLI_NAME}
  else
    command=$1
    commandList+=("${command}")
    shift
  fi

  if [ -z "${command}" ]; then
    bashcli-log-error "No command given"
    return 1
  fi

  bashcli-log-debug "${commandList[*]}"
  bashcli-command-resolve "${commandList[@]}" || return 1
  commandDir=$REPLY

  BASHCLI_COMMAND_STACK+=("${command}")
  # shellcheck source=/dev/null
  . "${commandDir}"/main "$@"
}

bashcli-command-subcommands() {
  local commandList=("$@")
  local IFS=/
  local commandPath="${commandList[*]:1}"
  local directory command commandDir
  local -A subcommands=()

  REPLY=()
  for directory in "${BASHCLI_COMMAND_DIRS[@]}"; do
    commandDir=${directory}/${commandPath}
    if [ -d "${commandDir}" ]; then
      for command in "${commandDir}"/*; do
        if [ -f "${command}"/main ]; then
          subcommands["${command##*/}"]=present
        fi
      done
    fi
  done
  REPLY=("${!subcommands[@]}")
}
