#!/usr/bin/env bash

bashcli-string-kebab-to-camel() {
  local input=$1
  local words output
  local IFS=' '
 
  mapfile -d- -t words <<< "${input}"

  output=${words[*]^}
  output=${output// /}
  output=${output,}

  REPLY="${output}"
}

bashcli-string-kebab-to-snake() {
  REPLY="${1//-/_}"
}

bashcli-string-camel-to-kebab() {
  local output=${1//[[:upper:]]/-&}
  REPLY=${output,,}
}

bashcli-string-snake-to-kebab() {
  REPLY="${1//_/-}"
}
