#!/usr/bin/env bash

bashcli-string-kebab-to-camel() {
  local input=$1
  local words output
  local IFS=' '
  
  mapfile -d- -t words <<< "${input}"

  output=${words[*]^}
  output=${output// /}
  output=${output,}

  printf "%s" "${output}"
}

bashcli-string-kebab-to-snake() {
  printf "%s" "${1//-/_}"
}

bashcli-string-camel-to-kebab() {
  local output=${1//[[:upper:]]/-&}
  output=${output,,}
  printf "%s" "${output}"
}

bashcli-string-snake-to-kebab() {
  printf "%s" "${1//_/-}"
}
