#!/usr/bin/env bash

declare -A options=()
declare -a parameters=()
declare templateBaseDir=templates/cli/command

bashcli-options-parse options parameters -- "$@"

case ${#parameters[@]} in
  0) bashcli-fatal "missing an argument" ;;
esac

# Initialize directories and templates.
if [ -d "${_BASHCLI_USER_DIR}/${templateBaseDir}" ]; then
  templateDir="${_BASHCLI_USER_DIR}/${templateBaseDir}"
elif [ -d "${BASHCLI_CLI_DIR}/${templateBaseDir}" ]; then
  templateDir="${BASHCLI_CLI_DIR}/${templateBaseDir}"
else
  # shellcheck disable=SC2153
  templateDir="${BASHCLI_DIR}/${templateBaseDir}"
fi

if [ ! -d "${templateDir}" ]; then
  bashcli-warn "template-directory does not exist: ${templateDir}"
fi

if [ "${options[directory]}" ]; then
  cliCommandDir=${options[directory]}
elif [ "${BASHCLI_DIST}" ] ; then
  cliCommandDir=${_BASHCLI_USER_DIR}/commands
else
  cliCommandDir=${BASHCLI_CLI_DIR}/commands
fi

declare -A templates=(
  @main            "${templateDir}"/@main
  @main.context    "${templateDir}"/@main.context
  @main.complete   "${templateDir}"/@main.complete
  command          "${templateDir}"/command
  command.context  "${templateDir}"/command.context
  command.complete "${templateDir}"/command.complete
)

bashcli-debug "using template-directory ${templateDir}"
mkdir --parents "${cliCommandDir}"
bashcli-debug "using command-directory ${cliCommandDir}"
bashcli-debug "normalizing commands"
bashcli-array-sort parameters -r
for parameter in "${parameters[@]}"; do
  path=$(realpath -ms --relative-to=. "./${parameter}")

  if [ "${path}" == . ]; then
    bashcli-fatal "command is empty: ${parameter}"
  fi

  path=${path//\//$'\n'}
  IFS=$'\n'
  readarray -t components <<<"${path}"

  for component in "${components[@]}"; do
    -bashcli-command-check-name "${component}"
  done

  IFS=' '
  command="${components[*]}"
  # Check if command is a prefix of an already existing one.
  for ((index = 0; index < ${#commands[@]}; ++index)); do
    if [[ "${commands[index]}" == "${command}"?( *) ]]; then
      command=
      break
    fi
  done

  if [ "${command}" ]; then
    commands+=("${command}")
    bashcli-debug "added command '${command}'"
  fi
done

bashcli-debug "verifing commands"
IFS=' '
for command in "${commands[@]}"; do
  # shellcheck disable=SC2206
  components=(${command})
  commandPath=${cliCommandDir}
  commandList=()
  for ((index = 0; index < ${#components[@]}; ++index)); do
    commandPath+="/${components[index]}"
    commandList+=("${components[index]}")
    if [ ! -e "${commandPath}" ]; then
      continue
    fi
    if [ ${index} -eq $((${#components[@]} - 1)) ]; then
      if [ -f "${commandPath}" ]; then
        if [ -z "${options[force]}" ]; then
          bashcli-fatal "command already exists: ${commandList[*]} (use --force to overwrite)"
        fi
      elif [ -d "${commandPath}" ]; then
        bashcli-fatal "command already exists as a non-terminal: ${commandList[*]}"
      else
        bashcli-fatal "file already exists: ${commandPath}"
      fi
    elif [ -f "${commandPath}" ]; then
      bashcli-fatal "command already exists as a terminal: ${commandList[*]}"
    elif [ ! -d "${commandPath}" ]; then
      bashcli-fatal "file already exists: ${commandPath}"
    fi
  done
done

bashcli-debug "creating commands"
for command in "${commands[@]}"; do
  # shellcheck disable=SC2206
  components=(${command})
  commandPath=${cliCommandDir}
  for ((index = 0; index < ${#components[@]}; ++index)); do
    commandPath+="/${components[index]}"
    if [ ${index} -lt $((${#components[@]} - 1)) ]; then
      if [ ! -d "${commandPath}" ]; then
        bashcli-debug "mkdir ${commandPath}"
        mkdir --parents "${commandPath}"
        for template in "${!templates[@]}"; do
          if [[ "${template}" == @main?(|.*) && -e "${templates[${template}]}" ]]; then
            bashcli-debug "cp ${templates[${template}]} -> ${commandPath}"
            cp -- "${templates[${template}]}" "${commandPath}"
          fi
        done
      fi
    else
      for template in "${!templates[@]}"; do
        if [[ "${template}" == command?(|.*) && -e "${templates[${template}]}" ]]; then
          templateDest=${commandPath}
          templateBasename=$(basename "${templates[${template}]}")
          if [[ "${templateBasename}" == *.* ]]; then
            templateExtension=${templateBasename##*.}
            templateDest+=.${templateExtension}
          fi
          bashcli-debug "cp ${templates[${template}]} -> ${templateDest}"
          cp -- "${templates[${template}]}" "${templateDest}"
        fi
      done
    fi
  done
done
