#!/usr/bin/env bash

declare parameters=()
# shellcheck disable=SC2034
declare -gA BASHCLI_CONFIG_CLI_COMMON_OPTIONS=()

bashcli-options-parse BASHCLI_CONFIG_CLI_COMMON_OPTIONS parameters -- "$@"
bashcli-command-exec "${parameters[@]}"
