#!/usr/bin/env bash

declare -A options=()
declare parameters=()

bashcli-options-parse options parameters -- "$@"

if [ "${options[scope]}" ]; then
  # shellcheck disable=2034
  BASHCLI_CONFIG_SCOPE=${options[scope]}
  bashcli-config-reinitialize
fi

bashcli-command-exec "${parameters[@]}"
