#!/usr/bin/env bash

bashcli-progress-hbar() {
  local doubleIndex=0
  local direction=1
  local clearLine=$'\033[50D'
  local barColor=$'\033[92m'
  local resetColor=$'\033[39m'
  local bar=($'\u2581' $'\u2582' $'\u2583' $'\u2584' $'\u2585' $'\u2586' $'\u2587' $'\u2588')

  trap 'tput cnorm; printf "%s" "${clearLine}" >&2' RETURN EXIT

  tput civis

  while IFS= read -r message; do
    printf "%s%s %s" "${clearLine}" "${barColor}${bar[${doubleIndex} / 2]}${resetColor}" "${message}" >&2
    ((doubleIndex += direction))
    if [[ ${doubleIndex} -ge $((2 * (${#bar[@]} - 1))) || ${doubleIndex} -le 0 ]]; then
      ((direction *= -1))
    fi
  done
}
