#!/usr/bin/env bash
# shellcheck disable=SC2034

declare -A options
declare -a parameters

bashcli-options-parse options parameters -- "$@" || exit 1

for parameter; do
  printf "%s\n" "${parameter}"
done
