#!/usr/bin/env bash

declare parentOptions=()
declare sharedOptions=()
declare parameters=()

bashcli-options-parse \
  '' \
  parameters \
  parentOptions=parent-option \
  sharedOptions=shared-option \
  -- "$@"

for ((index = 0; index < ${#parentOptions[@]}; ++index)); do
  echo "parent-option[${index}]=${parentOptions[index]}"
done
for ((index = 0; index < ${#sharedOptions[@]}; ++index)); do
  echo "parent-shared-option[${index}]=${sharedOptions[index]}"
done

if [ ${#parameters[@]} -gt 0 ]; then
  bashcli-command-exec "${parameters[@]}"
fi
