#!/usr/bin/env bash

#shellcheck disable=SC2034
declare -A options=()
declare parentOptions=()
declare sharedOptions=()
declare parameters=()

bashcli-options-parse \
  options \
  parameters \
  parentOptions=parent-option \
  sharedOptions=shared-option \
  -- "$@"

for ((index = 0; index < ${#parentOptions[@]}; ++index)); do
  echo "parent-option[${index}]=${parentOptions[index]}"
done
for ((index = 0; index < ${#sharedOptions[@]}; ++index)); do
  echo "parent-shared-option[${index}]=${sharedOptions[index]}"
done

bashcli-command-exec "${parameters[@]}"
