#!/usr/bin/env bash

declare childOptions=()
declare sharedOptions=()
declare parameters=()

bashcli-options-parse \
  '' \
  parameters \
  childOptions=child-option \
  sharedOptions=shared-option \
  -- "$@"

for ((index = 0; index < ${#childOptions[@]}; ++index)); do
  echo "child-option[${index}]=${childOptions[index]}"
done
for ((index = 0; index < ${#sharedOptions[@]}; ++index)); do
  echo "child-shared-option[${index}]=${sharedOptions[index]}"
done
for ((index = 0; index < ${#parameters[@]}; ++index)); do
  echo "parameter[${index}]=${parameters[index]}"
done
