#!/usr/bin/env bash

# shellcheck disable=SC2155

export BASHCLI_CLI_SCRIPT=$0
export BASHCLI_CLI_DIR="$(dirname "$0")/cli-dir"
BASHCLI_DIR=${BASHCLI_DIR:-"$(dirname "$0")/../../../../src"}

exec "${BASHCLI_DIR}"/bashcli "$@"
