#!/usr/bin/env bash

bashcli-load-library bashcli/cache

declare -A options=()
#shellcheck disable=SC2034
declare parameters=()
declare keyFn=cli-cache-key-fn

bashcli-options-parse options parameters -- "$@" || exit 1

cli-cache-key-fn() {
  local name=$1
  local keyFile=$2

  printf "%s" "${options[key]}" > "${keyFile}"
}

if [ -z "${options[key]}" ]; then
  keyFn=
fi

bashcli-cache-put "${options[name]}" "${options[value]}" ${keyFn}
