#!/usr/bin/env bash

bashcli-tools-log-rotate() {
  local filename
  local extension
  local pattern
  local maxKept=3

  while getopts "p:m:" option "$@"; do
    case ${option} in
      p) pattern=${OPTARG};;
      m) maxKept=${OPTARG};;
      *) return 1;;
    esac
  done

  shift "$((OPTIND - 1))"
  if [ $# -ne 1 ]; then
    bashcli-error "require exactly one parameter: $*"
    return 1
  fi
  filename=$1
  extension=${filename##*.}
  if [ -z "${pattern}" ]; then
    pattern=${filename%.*}.%s${extension+.}${extension}
  fi

  local patternWithoutPlaceholder=${pattern//%s/}
  if [ "${#patternWithoutPlaceholder}" -ne $((${#pattern} - 2)) ]; then
    bashcli-error "pattern must contain exactly one placeholder (%s): ${pattern}"
    return 1
  fi

  local index newerFile olderFile
  for ((index = maxKept; index > 0; --index)); do
    printf -v olderFile "${pattern}" "${index}"
    if [ ${index} -eq 1 ]; then
      newerFile=${filename}
    else
      printf -v newerFile "${pattern}" $((index - 1))
    fi

    if [ -f "${newerFile}" ]; then
      bashcli-debug "${newerFile} -> ${olderFile}"
      mv "${newerFile}" "${olderFile}"
    fi
  done

  return 0
}
