#!/usr/bin/env bash

if [[ ${BASH_VERSINFO[0]} -lt 5
          || (${BASH_VERSINFO[0]} -eq 5 && ${BASH_VERSINFO[1]} -lt 1) ]]; then
  echo "bash >= 5.1 required: ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" >&2
  exit 1
fi

shopt -s extglob nullglob
set -eo pipefail

# shellcheck disable=SC2034
export BASHCLI_VERSION=0.0.1
export BASHCLI_CLI_SCRIPT=${BASHCLI_CLI_SCRIPT:-"$0"}
if [[ "${BASHCLI_CLI_SCRIPT}" != /* ]]; then
  BASHCLI_CLI_SCRIPT=${PWD}/${BASHCLI_CLI_SCRIPT%./}
fi
export BASHCLI_CLI_DIR=${BASHCLI_CLI_SCRIPT%/*}
export BASHCLI_CLI_NAME=${BASHCLI_CLI_SCRIPT##*/}
export BASHCLI_DIR=$(realpath "$0")
BASHCLI_DIR=${BASHCLI_DIR%/*}

. "${BASHCLI_DIR}"/lib/bashcli/init
if [ "${BASHCLI_CLI_NAME}" != bashcli ]; then
  [ -f "${BASHCLI_CLI_DIR}/lib/${BASHCLI_CLI_NAME}/init" ] &&
    . "${BASHCLI_CLI_DIR}/lib/${BASHCLI_CLI_NAME}/init"
fi

-bashcli-command-loop . "$@"
