#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090,SC1091

BASHCLI_VERSION=0.0.1
BASHCLI_CLI_SCRIPT=${BASHCLI_CLI_SCRIPT:-$(realpath -s "$0")}
BASHCLI_CLI_DIR=$(dirname "${BASHCLI_CLI_SCRIPT}")
BASHCLI_CLI_NAME=$(basename "${BASHCLI_CLI_SCRIPT}")
BASHCLI_DIR=$(dirname "$(realpath "$0")")

. "${BASHCLI_DIR}"/lib/bashcli/init
if [ "${BASHCLI_CLI_NAME}" != bashcli ]; then
  [ -f "${BASHCLI_CLI_DIR}/lib/${BASHCLI_CLI_NAME}/init" ] &&
    . "${BASHCLI_CLI_DIR}/lib/${BASHCLI_CLI_NAME}/init"
fi

bashcli-command-exec-now . "$@"
while [ ${#BASHCLI_COMMAND_NEXT[@]} -gt 0 ]; do
  bashcli-command-exec-next || exit $?
done
