#!/usr/bin/env bash

bashcli-debug "Test subcommand called with arguments $*"

declare -A options=()
declare parameters=()
declare -a xmultiOptionOptions=()

bashcli-options-parse options parameters xmultiOptionOptions -- "$@" || {
  bashcli-fatal "Failed to parse options"
}

bashcli-debug "Options successfully parsed"

declare -p options
declare -p parameters
declare -p xmultiOptionOptions
